import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import "./globals.css";

import Setup from "./Setup";

export const metadata = {
  title: "CHIC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Setup />

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
